development: true



collections:
  law:
    output: true
    permalink: /info/law/:collection/:path
    title: Law
#  map:
#    output: true
#    permalink: /:collection/:path
#    title: Map
  sources:
    output: true
    permalink: /info/sources/:collection/:path
    title: Sources
    