development: true



collections:
  people:
    output: true
    permalink: /info/:collection/:path
    title: People
  org:
    output: true
    permalink: /info/:collection/:path
    title: Organization
  gov:
    output: true
    permalink: /info/:collection/:path
    title: Government
  law:
    output: true
    permalink: /info/:collection/:path
    title: Law
#  map:
#    output: true
#    permalink: /:collection/:path
#    title: Map
  sources:
    output: true
    permalink: /info/:collection/:path
    title: Sources
    